// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: widevine_pssh.proto

package com.pallycon.wowza;


public final class WidevinePSSH {
  private WidevinePSSH() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WidevineCencHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WidevineCencHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    boolean hasAlgorithm();
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    WidevineCencHeader.Algorithm getAlgorithm();

    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getKeyIdList();
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    int getKeyIdCount();
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    com.google.protobuf.ByteString getKeyId(int index);

    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     *Contentprovidername.
     * </pre>
     */
    boolean hasProvider();
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     *Contentprovidername.
     * </pre>
     */
    String getProvider();
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     *Contentprovidername.
     * </pre>
     */
    com.google.protobuf.ByteString
        getProviderBytes();

    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     *Acontentidentifier,specifiedbycontentprovider.
     * </pre>
     */
    boolean hasContentId();
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     *Acontentidentifier,specifiedbycontentprovider.
     * </pre>
     */
    com.google.protobuf.ByteString getContentId();

    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
     *differentiatecontentkeysusedbyanasset.
     * </pre>
     */
    boolean hasTrackType();
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
     *differentiatecontentkeysusedbyanasset.
     * </pre>
     */
    String getTrackType();
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
     *differentiatecontentkeysusedbyanasset.
     * </pre>
     */
    com.google.protobuf.ByteString
        getTrackTypeBytes();

    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     *Thenameofaregisteredpolicytobeusedforthisasset.
     * </pre>
     */
    boolean hasPolicy();
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     *Thenameofaregisteredpolicytobeusedforthisasset.
     * </pre>
     */
    String getPolicy();
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     *Thenameofaregisteredpolicytobeusedforthisasset.
     * </pre>
     */
    com.google.protobuf.ByteString
        getPolicyBytes();

    /**
     * <code>optional uint32 crypto_period_index = 7;</code>
     *
     * <pre>
     *Cryptoperiodindex,formediausingkeyrotation.
     * </pre>
     */
    boolean hasCryptoPeriodIndex();
    /**
     * <code>optional uint32 crypto_period_index = 7;</code>
     *
     * <pre>
     *Cryptoperiodindex,formediausingkeyrotation.
     * </pre>
     */
    int getCryptoPeriodIndex();
  }
  /**
   * Protobuf type {@code WidevineCencHeader}
   */
  public static final class WidevineCencHeader extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:WidevineCencHeader)
      WidevineCencHeaderOrBuilder {
    // Use WidevineCencHeader.newBuilder() to construct.
    private WidevineCencHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WidevineCencHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WidevineCencHeader defaultInstance;
    public static WidevineCencHeader getDefaultInstance() {
      return defaultInstance;
    }

    public WidevineCencHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WidevineCencHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Algorithm value = Algorithm.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                algorithm_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                keyId_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              keyId_.add(input.readBytes());
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              provider_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              contentId_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              trackType_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              policy_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              cryptoPeriodIndex_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          keyId_ = java.util.Collections.unmodifiableList(keyId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_WidevineCencHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_WidevineCencHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WidevineCencHeader.class, Builder.class);
    }

    public static com.google.protobuf.Parser<WidevineCencHeader> PARSER =
        new com.google.protobuf.AbstractParser<WidevineCencHeader>() {
      public WidevineCencHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WidevineCencHeader(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<WidevineCencHeader> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code WidevineCencHeader.Algorithm}
     */
    public enum Algorithm
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNENCRYPTED = 0;</code>
       */
      UNENCRYPTED(0, 0),
      /**
       * <code>AESCTR = 1;</code>
       */
      AESCTR(1, 1),
      ;

      /**
       * <code>UNENCRYPTED = 0;</code>
       */
      public static final int UNENCRYPTED_VALUE = 0;
      /**
       * <code>AESCTR = 1;</code>
       */
      public static final int AESCTR_VALUE = 1;


      public final int getNumber() { return value; }

      public static Algorithm valueOf(int value) {
        switch (value) {
          case 0: return UNENCRYPTED;
          case 1: return AESCTR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
              public Algorithm findValueByNumber(int number) {
                return Algorithm.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return WidevineCencHeader.getDescriptor().getEnumTypes().get(0);
      }

      private static final Algorithm[] VALUES = values();

      public static Algorithm valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Algorithm(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:WidevineCencHeader.Algorithm)
    }

    private int bitField0_;
    public static final int ALGORITHM_FIELD_NUMBER = 1;
    private Algorithm algorithm_;
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    public boolean hasAlgorithm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
     */
    public Algorithm getAlgorithm() {
      return algorithm_;
    }

    public static final int KEY_ID_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> keyId_;
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getKeyIdList() {
      return keyId_;
    }
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    public int getKeyIdCount() {
      return keyId_.size();
    }
    /**
     * <code>repeated bytes key_id = 2;</code>
     */
    public com.google.protobuf.ByteString getKeyId(int index) {
      return keyId_.get(index);
    }

    public static final int PROVIDER_FIELD_NUMBER = 3;
    private Object provider_;
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     *Contentprovidername.
     * </pre>
     */
    public boolean hasProvider() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     *Contentprovidername.
     * </pre>
     */
    public String getProvider() {
      Object ref = provider_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          provider_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string provider = 3;</code>
     *
     * <pre>
     *Contentprovidername.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getProviderBytes() {
      Object ref = provider_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        provider_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString contentId_;
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     *Acontentidentifier,specifiedbycontentprovider.
     * </pre>
     */
    public boolean hasContentId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes content_id = 4;</code>
     *
     * <pre>
     *Acontentidentifier,specifiedbycontentprovider.
     * </pre>
     */
    public com.google.protobuf.ByteString getContentId() {
      return contentId_;
    }

    public static final int TRACK_TYPE_FIELD_NUMBER = 5;
    private Object trackType_;
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
     *differentiatecontentkeysusedbyanasset.
     * </pre>
     */
    public boolean hasTrackType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
     *differentiatecontentkeysusedbyanasset.
     * </pre>
     */
    public String getTrackType() {
      Object ref = trackType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          trackType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string track_type = 5;</code>
     *
     * <pre>
     *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
     *differentiatecontentkeysusedbyanasset.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTrackTypeBytes() {
      Object ref = trackType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        trackType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POLICY_FIELD_NUMBER = 6;
    private Object policy_;
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     *Thenameofaregisteredpolicytobeusedforthisasset.
     * </pre>
     */
    public boolean hasPolicy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     *Thenameofaregisteredpolicytobeusedforthisasset.
     * </pre>
     */
    public String getPolicy() {
      Object ref = policy_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          policy_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string policy = 6;</code>
     *
     * <pre>
     *Thenameofaregisteredpolicytobeusedforthisasset.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPolicyBytes() {
      Object ref = policy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        policy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CRYPTO_PERIOD_INDEX_FIELD_NUMBER = 7;
    private int cryptoPeriodIndex_;
    /**
     * <code>optional uint32 crypto_period_index = 7;</code>
     *
     * <pre>
     *Cryptoperiodindex,formediausingkeyrotation.
     * </pre>
     */
    public boolean hasCryptoPeriodIndex() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint32 crypto_period_index = 7;</code>
     *
     * <pre>
     *Cryptoperiodindex,formediausingkeyrotation.
     * </pre>
     */
    public int getCryptoPeriodIndex() {
      return cryptoPeriodIndex_;
    }

    private void initFields() {
      algorithm_ = Algorithm.UNENCRYPTED;
      keyId_ = java.util.Collections.emptyList();
      provider_ = "";
      contentId_ = com.google.protobuf.ByteString.EMPTY;
      trackType_ = "";
      policy_ = "";
      cryptoPeriodIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, algorithm_.getNumber());
      }
      for (int i = 0; i < keyId_.size(); i++) {
        output.writeBytes(2, keyId_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getProviderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, contentId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getTrackTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getPolicyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(7, cryptoPeriodIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, algorithm_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < keyId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(keyId_.get(i));
        }
        size += dataSize;
        size += 1 * getKeyIdList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProviderBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, contentId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTrackTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getPolicyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, cryptoPeriodIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static WidevineCencHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WidevineCencHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WidevineCencHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WidevineCencHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WidevineCencHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WidevineCencHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static WidevineCencHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static WidevineCencHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static WidevineCencHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WidevineCencHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(WidevineCencHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WidevineCencHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WidevineCencHeader)
        WidevineCencHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_WidevineCencHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_WidevineCencHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WidevineCencHeader.class, Builder.class);
      }

      // Construct using WidevineCencHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        algorithm_ = Algorithm.UNENCRYPTED;
        bitField0_ = (bitField0_ & ~0x00000001);
        keyId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        provider_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        contentId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        trackType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        policy_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        cryptoPeriodIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_WidevineCencHeader_descriptor;
      }

      public WidevineCencHeader getDefaultInstanceForType() {
        return WidevineCencHeader.getDefaultInstance();
      }

      public WidevineCencHeader build() {
        WidevineCencHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WidevineCencHeader buildPartial() {
        WidevineCencHeader result = new WidevineCencHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.algorithm_ = algorithm_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          keyId_ = java.util.Collections.unmodifiableList(keyId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.keyId_ = keyId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.provider_ = provider_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentId_ = contentId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.trackType_ = trackType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.policy_ = policy_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.cryptoPeriodIndex_ = cryptoPeriodIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WidevineCencHeader) {
          return mergeFrom((WidevineCencHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WidevineCencHeader other) {
        if (other == WidevineCencHeader.getDefaultInstance()) return this;
        if (other.hasAlgorithm()) {
          setAlgorithm(other.getAlgorithm());
        }
        if (!other.keyId_.isEmpty()) {
          if (keyId_.isEmpty()) {
            keyId_ = other.keyId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureKeyIdIsMutable();
            keyId_.addAll(other.keyId_);
          }
          onChanged();
        }
        if (other.hasProvider()) {
          bitField0_ |= 0x00000004;
          provider_ = other.provider_;
          onChanged();
        }
        if (other.hasContentId()) {
          setContentId(other.getContentId());
        }
        if (other.hasTrackType()) {
          bitField0_ |= 0x00000010;
          trackType_ = other.trackType_;
          onChanged();
        }
        if (other.hasPolicy()) {
          bitField0_ |= 0x00000020;
          policy_ = other.policy_;
          onChanged();
        }
        if (other.hasCryptoPeriodIndex()) {
          setCryptoPeriodIndex(other.getCryptoPeriodIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WidevineCencHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WidevineCencHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Algorithm algorithm_ = Algorithm.UNENCRYPTED;
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public boolean hasAlgorithm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public Algorithm getAlgorithm() {
        return algorithm_;
      }
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public Builder setAlgorithm(Algorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        algorithm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .WidevineCencHeader.Algorithm algorithm = 1;</code>
       */
      public Builder clearAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        algorithm_ = Algorithm.UNENCRYPTED;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> keyId_ = java.util.Collections.emptyList();
      private void ensureKeyIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          keyId_ = new java.util.ArrayList<com.google.protobuf.ByteString>(keyId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getKeyIdList() {
        return java.util.Collections.unmodifiableList(keyId_);
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public int getKeyIdCount() {
        return keyId_.size();
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public com.google.protobuf.ByteString getKeyId(int index) {
        return keyId_.get(index);
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder setKeyId(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIdIsMutable();
        keyId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder addKeyId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureKeyIdIsMutable();
        keyId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder addAllKeyId(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureKeyIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, keyId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes key_id = 2;</code>
       */
      public Builder clearKeyId() {
        keyId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private Object provider_ = "";
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       *Contentprovidername.
       * </pre>
       */
      public boolean hasProvider() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       *Contentprovidername.
       * </pre>
       */
      public String getProvider() {
        Object ref = provider_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            provider_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       *Contentprovidername.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getProviderBytes() {
        Object ref = provider_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          provider_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       *Contentprovidername.
       * </pre>
       */
      public Builder setProvider(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        provider_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       *Contentprovidername.
       * </pre>
       */
      public Builder clearProvider() {
        bitField0_ = (bitField0_ & ~0x00000004);
        provider_ = getDefaultInstance().getProvider();
        onChanged();
        return this;
      }
      /**
       * <code>optional string provider = 3;</code>
       *
       * <pre>
       *Contentprovidername.
       * </pre>
       */
      public Builder setProviderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        provider_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contentId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       *Acontentidentifier,specifiedbycontentprovider.
       * </pre>
       */
      public boolean hasContentId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       *Acontentidentifier,specifiedbycontentprovider.
       * </pre>
       */
      public com.google.protobuf.ByteString getContentId() {
        return contentId_;
      }
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       *Acontentidentifier,specifiedbycontentprovider.
       * </pre>
       */
      public Builder setContentId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        contentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content_id = 4;</code>
       *
       * <pre>
       *Acontentidentifier,specifiedbycontentprovider.
       * </pre>
       */
      public Builder clearContentId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        contentId_ = getDefaultInstance().getContentId();
        onChanged();
        return this;
      }

      private Object trackType_ = "";
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
       *differentiatecontentkeysusedbyanasset.
       * </pre>
       */
      public boolean hasTrackType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
       *differentiatecontentkeysusedbyanasset.
       * </pre>
       */
      public String getTrackType() {
        Object ref = trackType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            trackType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
       *differentiatecontentkeysusedbyanasset.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTrackTypeBytes() {
        Object ref = trackType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          trackType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
       *differentiatecontentkeysusedbyanasset.
       * </pre>
       */
      public Builder setTrackType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        trackType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
       *differentiatecontentkeysusedbyanasset.
       * </pre>
       */
      public Builder clearTrackType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        trackType_ = getDefaultInstance().getTrackType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string track_type = 5;</code>
       *
       * <pre>
       *Tracktype.AcceptablevaluesareSD,HDandAUDIO.Usedto
       *differentiatecontentkeysusedbyanasset.
       * </pre>
       */
      public Builder setTrackTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        trackType_ = value;
        onChanged();
        return this;
      }

      private Object policy_ = "";
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       *Thenameofaregisteredpolicytobeusedforthisasset.
       * </pre>
       */
      public boolean hasPolicy() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       *Thenameofaregisteredpolicytobeusedforthisasset.
       * </pre>
       */
      public String getPolicy() {
        Object ref = policy_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            policy_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       *Thenameofaregisteredpolicytobeusedforthisasset.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPolicyBytes() {
        Object ref = policy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          policy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       *Thenameofaregisteredpolicytobeusedforthisasset.
       * </pre>
       */
      public Builder setPolicy(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        policy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       *Thenameofaregisteredpolicytobeusedforthisasset.
       * </pre>
       */
      public Builder clearPolicy() {
        bitField0_ = (bitField0_ & ~0x00000020);
        policy_ = getDefaultInstance().getPolicy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string policy = 6;</code>
       *
       * <pre>
       *Thenameofaregisteredpolicytobeusedforthisasset.
       * </pre>
       */
      public Builder setPolicyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        policy_ = value;
        onChanged();
        return this;
      }

      private int cryptoPeriodIndex_ ;
      /**
       * <code>optional uint32 crypto_period_index = 7;</code>
       *
       * <pre>
       *Cryptoperiodindex,formediausingkeyrotation.
       * </pre>
       */
      public boolean hasCryptoPeriodIndex() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 crypto_period_index = 7;</code>
       *
       * <pre>
       *Cryptoperiodindex,formediausingkeyrotation.
       * </pre>
       */
      public int getCryptoPeriodIndex() {
        return cryptoPeriodIndex_;
      }
      /**
       * <code>optional uint32 crypto_period_index = 7;</code>
       *
       * <pre>
       *Cryptoperiodindex,formediausingkeyrotation.
       * </pre>
       */
      public Builder setCryptoPeriodIndex(int value) {
        bitField0_ |= 0x00000040;
        cryptoPeriodIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 crypto_period_index = 7;</code>
       *
       * <pre>
       *Cryptoperiodindex,formediausingkeyrotation.
       * </pre>
       */
      public Builder clearCryptoPeriodIndex() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cryptoPeriodIndex_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WidevineCencHeader)
    }

    static {
      defaultInstance = new WidevineCencHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WidevineCencHeader)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WidevineCencHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WidevineCencHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023widevine_pssh.proto\"\347\001\n\022WidevineCencHe" +
      "ader\0220\n\talgorithm\030\001 \001(\0162\035.WidevineCencHe" +
      "ader.Algorithm\022\016\n\006key_id\030\002 \003(\014\022\020\n\010provid" +
      "er\030\003 \001(\t\022\022\n\ncontent_id\030\004 \001(\014\022\022\n\ntrack_ty" +
      "pe\030\005 \001(\t\022\016\n\006policy\030\006 \001(\t\022\033\n\023crypto_perio" +
      "d_index\030\007 \001(\r\"(\n\tAlgorithm\022\017\n\013UNENCRYPTE" +
      "D\020\000\022\n\n\006AESCTR\020\001B!\n\021"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_WidevineCencHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WidevineCencHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_WidevineCencHeader_descriptor,
        new String[] { "Algorithm", "KeyId", "Provider", "ContentId", "TrackType", "Policy", "CryptoPeriodIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
